# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20170731_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='flat',
            field=models.BooleanField(default=True),
        ),
    ]
