# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 03:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20170731_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='flat',
            new_name='flat_rate',
        ),
    ]
