# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20170731_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.CharField(default='default.jpg', max_length=30),
            preserve_default=False,
        ),
    ]
